# Generated by Django 3.1.5 on 2021-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTheNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_algo_condense', models.TextField(null=True)),
                ('title', models.CharField(max_length=256)),
                ('publication', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('url', models.CharField(max_length=1024)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
